namespace SIM.Mvvm.CodeGenerator
{

    public class AutoGeneratedProperty
    {
        public bool IsValid => string.IsNullOrWhiteSpace(this.ExcludeMessage);

        public string ExcludeMessage { get; set; }

        public string PropertyTypeNamespace { get; set; }

        public string PropertyType { get; set; }

        public string PropertyName { get; set; }

        public string ModelType { get; set; }

        public string ModelName { get; set; }
    }
}
