namespace SIM.Mvvm.CodeGenerator
{

    public class AutoGeneratedProperty
    {
        public string PropertyType { get; set; }

        public string PropertyName { get; set; }

        public string ModelType { get; set; }

        public string ModelName { get; set; }
    }
}
